import path from "node:path";
import fs from "node:fs/promises";
import fsSync from "node:fs";
import { camelCase } from "lodash-es";
import fg from "fast-glob";
import { createTrailingRunner } from "./utils";

let cachedFolderSet: Set<string> | null = null;

export function generateModuleMapContent(
  folders: string[],
  rootDir: string,
  typeDir: string,
  modulesPathStr: string,
): string {
  if (folders.length === 0) {
    return `// This file is generated by @path-ioc/unplugin, do not edit.

declare global {
  interface ModuleMap {
    [key: string]: any;
  }
  interface ModularContainer {
    [key: string]: any;
  }
}

export {};
`;
  }

  const dtsDir = path.resolve(rootDir, typeDir);
  const modulesRoot = path.resolve(rootDir, modulesPathStr);

  const moduleFolderMap = new Map<string, string>();
  const shortNameFullNamesMap = new Map<string, string[]>();

  folders.forEach((relDir) => {
    const dirPath = path.resolve(rootDir, relDir);
    let importRelPath = path.relative(dtsDir, dirPath).replace(/\\/g, "/");
    if (!importRelPath.startsWith(".")) {
      importRelPath = "./" + importRelPath;
    }

    const logicalPath = path.relative(modulesRoot, dirPath).replace(/\\/g, "/");
    const folderName = logicalPath.split("/").pop();
    if (!folderName) return;

    const moduleName = folderName.charAt(0) + camelCase(folderName).slice(1);
    const logicalDir = logicalPath.substring(0, logicalPath.lastIndexOf(folderName));
    const moduleFullName = `/${logicalDir}${moduleName}`;

    moduleFolderMap.set(moduleFullName, importRelPath);
    moduleFolderMap.set(moduleName, importRelPath);

    const fullNames = shortNameFullNamesMap.get(moduleName) || [];
    fullNames.push(moduleFullName);
    shortNameFullNamesMap.set(moduleName, fullNames);
  });

  // 过滤冲突的短名
  for (const [shortName, fullNames] of shortNameFullNamesMap.entries()) {
    if (fullNames.length > 1) {
      moduleFolderMap.delete(shortName);
    }
  }

  const entries: string[] = [];
  const containerEntries: string[] = [];

  for (const [key, relPath] of moduleFolderMap.entries()) {
    entries.push(`    "${key}": typeof import("${relPath}/index");`);
    containerEntries.push(`    "${key}": Awaited<ReturnType<typeof import("${relPath}/index")["main"]>>;`);
  }

  return `// This file is generated by @path-ioc/unplugin, do not edit.
/// <reference types="@path-ioc/unplugin/virtual" />

declare global {
  interface ModuleMap {
    [key: string]: any;
${entries.join("\n")}
  }
  interface ModularContainer {
    [key: string]: any;
${containerEntries.join("\n")}
  }
}

export {};
`;
}

// 生成类型定义的底层逻辑
const doGenerateTypeDefinitions = async (
  rootDir: string,
  typeDir: string,
  modulesPathStr: string,
) => {
  try {
    const modulesRoot = path.resolve(rootDir, modulesPathStr);
    const dotIgnorePath = path.resolve(rootDir, ".gitignore");
    try {
      const dotIgnoreContent = await fs.readFile(dotIgnorePath, "utf-8");
      if (!dotIgnoreContent.includes("ignore.*")) {
        await fs.appendFile(
          dotIgnorePath,
          `\n\n# @path-ioc/unplugin\nignore.*\n`,
        );
      }
    } catch (e) {
      /* .gitignore 不存在则忽略 */
    }

    const dtsDir = path.resolve(rootDir, typeDir);
    await fs.mkdir(dtsDir, { recursive: true });
    const dtsPath = path.resolve(dtsDir, "ignore.modular.d.ts");

    // 使用 fast-glob 进行更高效的扫描
    const searchPattern = path.posix.join(modulesRoot.replace(/\\/g, "/"), "**/index.{ts,tsx}");
    const files = await fg(searchPattern, { absolute: true });
    const folders = files.map((f) => path.relative(rootDir, path.dirname(f)));

    // 🚀 极致性能：用 Set 缓存模块目录。无需 sort()，也无需 join("|") 拼字符串
    if (cachedFolderSet && cachedFolderSet.size === folders.length && fsSync.existsSync(dtsPath)) {
      let isIdentical = true;
      for (let i = 0; i < folders.length; i++) {
        if (!cachedFolderSet.has(folders[i])) {
          isIdentical = false;
          break;
        }
      }
      if (isIdentical) {
        return; // 目录无增减无变动，0 毫秒极速退出！
      }
    }
    cachedFolderSet = new Set(folders);

    const content = generateModuleMapContent(folders, rootDir, typeDir, modulesPathStr);
    await fs.writeFile(dtsPath, content, { flag: "w" });
  } catch (e) {
    // 异常安全保护，确保高频文件系统变动下构建服务绝对不崩溃
  }
};

export const generateTypeDefinitions = createTrailingRunner(doGenerateTypeDefinitions);
