import { camelCase } from "lodash-es";

type InternalModularContainer = Record<string, unknown> & {
  $logs?: string[];
};

// --- 常量定义与配置 ---

const DEFAULT_ORDER = 99999;

// Regex removed, keeping pure logical keys

// --- 类型定义 ---

export interface IOCModule {
  main: (
    modularContainer: InternalModularContainer,
    moduleDeclarationNames: string[],
  ) => Promise<unknown> | unknown;
  dependencies?: string[] | ((moduleDeclarationNames: string[]) => string[]);
  order?: number;
  skip?: boolean;
}

export interface ModuleDeclaration {
  name: string; // 短名称，用于依赖解析
  fullName: string; // 完整路径名称，全局唯一
  main: (
    modularContainer: InternalModularContainer,
    moduleDeclarationNames: string[],
  ) => Promise<unknown> | unknown;
  dependencies: string[];
  order: number;
  skip?: boolean;
  rawModule: IOCModule;
}

export interface CompiledModuleGraph {
  sortedDeclarations: ModuleDeclaration[];
  resolvedDepsMap: Map<string, string[]>;
  fullNameToModuleMap: Map<string, ModuleDeclaration>;
  moduleDeclarationNames: string[];
  shortNameToFullNameMap: Map<string, string | null>;
}

// --- 类型辅助守卫 (防止 any 逃逸) ---
const isPromise = (value: unknown): value is Promise<unknown> => {
  return (
    value !== null &&
    (typeof value === "object" || typeof value === "function") &&
    "then" in value &&
    typeof (value as Record<string, unknown>).then === "function"
  );
};

// --- 静态图编译函数 (一次运行，纯同步纳秒级完成) ---

/**
 * 编译模块依赖图 (纯同步执行)。
 * 提取全名/短名映射，解析并映射依赖关系，运行 DFS 循环依赖检测并生成拓扑排序。
 *
 * @param modules - 模块加载器列表，每个包含 key 和 getter
 * @returns 编译后的静态模块依赖图
 */
export const compileModuleGraph = (
  modules: { key: string; module: IOCModule }[],
): CompiledModuleGraph => {
  // --- 阶段一: 预解析模块全名与短名称 (纯同步，统一解析，杜绝重复正则开销与非空断言) ---
  const parsedNames = modules.map(({ key }) => {
    // The key is now a pure logical path, e.g., /userCenter or /common/auth
    const parts = key.split("/");
    let folderName = parts.pop();
    if (!folderName) {
      if (parts.length > 0) {
        folderName = parts.pop()!;
      } else {
        console.log("THROWING FOR KEY:", key, "PARTS:", parts, "FOLDERNAME:", folderName);
        throw new Error(`Could not parse module name from key: ${key}`);
      }
    }
    
    // We expect folderName to already be camelCase if it was generated by pack plugin,
    // but unplugin might just strip the prefix and yield raw folder names.
    // For safety, we camelCase it here again to form shortName.
    const shortName = folderName[0] + camelCase(folderName).slice(1);
    
    // The key itself is the fullName.
    // However, if the key was something like /common/auth-module, 
    // we want fullName to reflect the camelCased shortName: /common/authModule.
    const modulePath = parts.length > 0 ? parts.join("/") + "/" : key.startsWith("/") ? "/" : "";
    const fullName = `${modulePath}${shortName}`;
    
    return {
      shortName,
      fullName,
    };
  });

  const moduleDeclarationNames = parsedNames.map((p) => p.fullName);

  // --- 阶段二: 获取所有模块声明 (纯同步解析) ---
  const processIOCModule = (
    iocModule: IOCModule,
    index: number,
  ): ModuleDeclaration => {
    if (!iocModule || typeof iocModule.main !== "function") {
      throw new Error(
        `[${parsedNames[index].fullName}] 'main' is not a function.`,
      );
    }

    const deps =
      typeof iocModule.dependencies === "function"
        ? iocModule.dependencies(moduleDeclarationNames)
        : iocModule.dependencies || [];

    if (!Array.isArray(deps)) {
      throw new Error(
        `[${parsedNames[index].fullName}] 'dependencies' must be an array or a function returning an array.`,
      );
    }

    return {
      name: parsedNames[index].shortName,
      fullName: parsedNames[index].fullName,
      main: iocModule.main,
      dependencies: deps,
      order: iocModule.order ?? DEFAULT_ORDER,
      skip: iocModule.skip,
      rawModule: iocModule,
    };
  };

  const allDeclarations: ModuleDeclaration[] = modules.map(({ module: mod }, i) => {
    return processIOCModule(mod, i);
  });

  // --- 阶段三: 解析依赖并映射短名称 ---
  const fullNameToModuleMap = new Map<string, ModuleDeclaration>();
  const shortNameToFullNameMap = new Map<string, string | null>();

  for (const mod of allDeclarations) {
    if (fullNameToModuleMap.has(mod.fullName)) {
      throw new Error(
        `[Configuration Error] Duplicate module fullName detected: '${mod.fullName}'.`,
      );
    }
    fullNameToModuleMap.set(mod.fullName, mod);

    if (!shortNameToFullNameMap.has(mod.name)) {
      shortNameToFullNameMap.set(mod.name, mod.fullName);
    } else {
      // 标记为有歧义
      shortNameToFullNameMap.set(mod.name, null);
    }
  }

  // 将每个模块声明中的 dependencies 解析为统一的 fullName 数组
  const resolvedDepsMap = new Map<string, string[]>();
  for (const mod of allDeclarations) {
    const resolvedDeps: string[] = [];
    for (const depName of mod.dependencies) {
      let resolvedFullName: string | undefined;

      if (fullNameToModuleMap.has(depName)) {
        resolvedFullName = depName;
      } else if (shortNameToFullNameMap.has(depName)) {
        const found = shortNameToFullNameMap.get(depName);
        if (found === null) {
          const conflictingModules = allDeclarations
            .filter((m) => m.name === depName)
            .map((m) => `'${m.fullName}'`)
            .join(" and ");
          throw new Error(
            `[Dependency Error] Module '${mod.fullName}' has an ambiguous dependency on '${depName}'. ` +
              `This short name is used by ${conflictingModules}. Please disambiguate by renaming the module (e.g. 'userService', 'adminService') or refactoring domain boundaries. Avoid hardcoding full paths in business dependencies as it is an architectural anti-pattern.`,
          );
        }
        resolvedFullName = found;
      }

      if (!resolvedFullName) {
        throw new Error(
          `[Dependency Error] Module '${mod.fullName}' depends on '${depName}', which was not found.`,
        );
      }

      if (resolvedFullName !== mod.fullName) {
        resolvedDeps.push(resolvedFullName);
      }
    }
    resolvedDepsMap.set(mod.fullName, resolvedDeps);
  }

  // --- 阶段四: 静态循环依赖检测与拓扑排序生成 (DFS + 栈路径) ---
  const visited = new Set<string>();
  const stack = new Set<string>();
  const topologicalOrder: string[] = [];

  const detectCycle = (fullName: string) => {
    if (stack.has(fullName)) {
      const pathArray = Array.from(stack);
      const cycleStartIndex = pathArray.indexOf(fullName);
      const cyclePath = pathArray
        .slice(cycleStartIndex)
        .concat(fullName)
        .join(" -> ");
      throw new Error(
        `[Circular Dependency] A cycle was detected: ${cyclePath}`,
      );
    }
    if (visited.has(fullName)) return;

    stack.add(fullName);
    const deps = resolvedDepsMap.get(fullName) || [];
    for (const dep of deps) {
      detectCycle(dep);
    }
    stack.delete(fullName);
    visited.add(fullName);
    topologicalOrder.push(fullName);
  };

  const sortedByOrder = [...allDeclarations].sort((a, b) => a.order - b.order);
  for (const mod of sortedByOrder) {
    detectCycle(mod.fullName);
  }

  // 严格按照拓扑排序的顺序（依赖项最前）触发流式加载
  const sortedDeclarations = [...allDeclarations].sort((a, b) => {
    return (
      topologicalOrder.indexOf(a.fullName) -
      topologicalOrder.indexOf(b.fullName)
    );
  });

  return {
    sortedDeclarations,
    resolvedDepsMap,
    fullNameToModuleMap,
    moduleDeclarationNames,
    shortNameToFullNameMap,
  };
};

// --- 基于图计算的动态容器填充函数 (并发无锁依赖解析器) ---

/**
 * 基于已编译的依赖图，动态实例化模块容器。
 *
 * @param compiledGraph - 编译后的静态依赖图描述
 * @param modularContainer - 需要填充实例的容器对象
 */
export const instantiateModuleContainer = async (
  compiledGraph: CompiledModuleGraph,
  modularContainer: Record<string, unknown> & { $logs?: string[] },
): Promise<void> => {
  if (!modularContainer.$logs) {
    modularContainer.$logs = [];
  }
  const logs = modularContainer.$logs;

  const {
    sortedDeclarations,
    resolvedDepsMap,
    fullNameToModuleMap,
    moduleDeclarationNames,
  } = compiledGraph;

  logs.push("Phase 5: Reactive execution flow starting...");

  // initPromises 严格声明为 Promise 容器映射，不存储任何同步原始值
  const initPromises = new Map<string, Promise<unknown>>();

  // instantiated 记录当前实例化周期内已经初始化完成的模块
  const instantiated = new Set<string>();

  // 统一提交模块结果：记录耗时、写入全名、安全挂载短名称并进行 AOP 守护
  const commitModuleResult = (
    mod: ModuleDeclaration,
    result: unknown,
    startTime: number,
  ) => {
    const cost = Date.now() - startTime;
    logs.push(`[Init] ${mod.fullName} initialized in ${cost}ms`);
    modularContainer[mod.fullName] = result;
    instantiated.add(mod.fullName);
    if (
      compiledGraph.shortNameToFullNameMap.get(mod.name) === mod.fullName &&
      !modularContainer.hasOwnProperty(mod.name)
    ) {
      modularContainer[mod.name] = result;
    }
  };

  const resolveModule = (fullName: string): Promise<unknown> | unknown => {
    // 1. 优先检查异步执行缓存，如果正在挂起或属于异步初始化，返回 Promise
    if (initPromises.has(fullName)) {
      return initPromises.get(fullName)!;
    }

    // 2. 检查当前生命周期内是否已同步写入，如果已同步写入，直接返回同步结果
    // 修复破坏性变更：不能直接用 modularContainer.hasOwnProperty，
    // 因为外界如果传入携带了旧数据的容器（比如 Hono 中 spread c.env.modularContainer），会导致旧实例被复用、串请求。
    if (instantiated.has(fullName)) {
      return modularContainer[fullName];
    }

    const mod = fullNameToModuleMap.get(fullName);
    if (!mod || mod.skip) {
      const p = Promise.resolve();
      initPromises.set(fullName, p);
      return p;
    }

    const deps = resolvedDepsMap.get(fullName) || [];

    // 性能优化：检查当前所有的前置依赖项是否已经【就绪】写回了容器。
    const allDepsReadySync = deps.every((dep) => {
      const depMod = fullNameToModuleMap.get(dep);
      if (!depMod) return true;
      if (depMod.skip) return true;
      return (
        instantiated.has(dep) ||
        (modularContainer.hasOwnProperty(dep) && !fullNameToModuleMap.has(dep)) // 允许从外部直接注入非动态模块的依赖
      );
    });

    if (allDepsReadySync) {
      const startTime = Date.now();
      const result = mod.main(modularContainer, moduleDeclarationNames);

      if (isPromise(result)) {
        // 异步 main：依旧使用 promise 链式异步处理，写入 initPromises
        const promise = (async () => {
          const finalResult = await result;
          commitModuleResult(mod, finalResult, startTime);
          return finalResult;
        })();
        initPromises.set(fullName, promise);
        return promise;
      } else {
        // 同步 main：直接原地同步写入并完成，零 Promise 包装，不入 initPromises 缓存，直接同步返回结果
        commitModuleResult(mod, result, startTime);
        return result;
      }
    }

    // 存在未完成的依赖（可能是异步模块），则进入常规的 Promise 链处理
    const promise = (async () => {
      // 对同一层级的依赖，按 order 权重从小到大排序优先触发解析
      const sortedDeps = [...deps].sort((a, b) => {
        const modA = fullNameToModuleMap.get(a);
        const modB = fullNameToModuleMap.get(b);
        return (modA?.order ?? DEFAULT_ORDER) - (modB?.order ?? DEFAULT_ORDER);
      });

      const depPromises = sortedDeps.map((dep) => resolveModule(dep));
      await Promise.all(depPromises);

      const startTime = Date.now();
      const result = await mod.main(modularContainer, moduleDeclarationNames);
      commitModuleResult(mod, result, startTime);
      return result;
    })();

    initPromises.set(fullName, promise);
    return promise;
  };

  const resultsOrPromises = sortedDeclarations.map((m) =>
    resolveModule(m.fullName),
  );

  // 时序与性能二重守护：检查返回的结果中是否包含未决 Promise。
  // 若全部为同步返回，直接绕过 Promise.all，确保 100% 同步直通运行。
  const hasPromise = resultsOrPromises.some(isPromise);
  if (hasPromise) {
    await Promise.all(resultsOrPromises);
  }

  logs.push("Initialization complete.");
};
